import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const robotoFont = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"]
})

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${robotoFont.className}`}>
        <Toaster position="bottom-center" reverseOrder={false}></Toaster>
        {children}
      </body>
    </html>
  );
}
